<wsdl:definitions name="booking"
	targetNamespace="http://example.com/booking/wsdl"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:inv="invoice.xsd"
	xmlns:recommend="recommendation.xsd">

	<wsdl:message name="destInput">
		<wsdl:part name="destination" type="xsd:string"/>
	</wsdl:message>
	
	<wsdl:message name="dateInput">
		<wsdl:part name="date" type="xsd:date"/>
	</wsdl:message>
	
	<wsdl:message name="attendeesInput">
		<wsdl:part name="attendees" type="xsd:integer"/>
	</wsdl:message>
	
	<wsdl:message name="confirmInput">
		<wsdl:part name="confirm" type="xsd:string"/>
	</wsdl:message>
	
	<wsdl:message name="recommendOutput">
		<wsdl:part name="placeRecommendation" type="recommend:recommendation"/>
	</wsdl:message>
	
	<wsdl:message name="bookTicket">
		<wsdl:part name="creditCardDetail" type="inv:credentialDetail"/>
	</wsdl:message>
	
	<wsdl:message name="purchaseInvoice">
		<wsdl:part name="purInvoice" type="inv:invoice"/>
	</wsdl:message>
	
	<wsdl:portType name="lookUpRecommend_PortType">
		<wsdl:operation name="lookUpRecommend">
			<wsdl:input message="destInput"/>
			<wsdl:input message="date"/>
			<wsdl:input message="attendeesInput"/>
			<wsdl:output message="recommendOutput"/>
		</wsdl:operation>	
	</wsdl:portType>
	
	<wsdl:portType name="purchaseTicket_PortType">
		<wsdl:operation name="purchaseTicket">
			<wsdl:input message="bookTicket"/>
			<wsdl:output message="invoice"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>